package com.mycompany.calculadoramaven;


import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Victor
 */
public class Calculadora extends javax.swing.JFrame {

    private double op1, op2;

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        myInit();
    }

    public void myInit(){
        
        bSuma.setName(ConstantesPrueba.BOTON_SUMAR);
        bResta.setName(ConstantesPrueba.BOTON_RESTAR);
        bMultiplica.setName(ConstantesPrueba.BOTON_MULTIPLICA);
        bDivide.setName(ConstantesPrueba.BOTON_DIVIDE);
        top1b.setName(ConstantesPrueba.TEXTFIELD_OP1_BOTON);
        top2b.setName(ConstantesPrueba.TEXTFIELD_OP2_BOTON);
        top1r.setName(ConstantesPrueba.TEXTFIELD_OP1_RADIO);
        top2r.setName(ConstantesPrueba.TEXTFIELD_OP2_RADIO);
        top1c.setName(ConstantesPrueba.TEXTFIELD_OP1_COMBO);
        top2c.setName(ConstantesPrueba.TEXTFIELD_OP2_COMBO);
        tabbedPanel.setName(ConstantesPrueba.PANEL);
        tbBotones.setName(ConstantesPrueba.PANEL_BOTONES);
        tbRadio.setName(ConstantesPrueba.PANEL_RADIO);
        tbCombo.setName(ConstantesPrueba.PANEL_COMBO);
        lResultB.setName(ConstantesPrueba.LABEL_RES_BOTON);
        lResultR.setName(ConstantesPrueba.LABEL_RES_RADIO);
        lResultC.setName(ConstantesPrueba.LABEL_RES_COMBO);
        rSumar.setName(ConstantesPrueba.RADIO_SUMAR);
        rRestar.setName(ConstantesPrueba.RADIO_RESTA);
        rMultiplicar.setName(ConstantesPrueba.RADIO_MULTIPLICA);
        rDividir.setName(ConstantesPrueba.RADIO_DIVIDE);
        cDecimales.setName(ConstantesPrueba.CHECKBOX);
        bEqualR.setName(ConstantesPrueba.BOTON_IGUAL_RADIO);
        bEqualC.setName(ConstantesPrueba.BOTON_IGUAL_COMBO);
        cOperaciones.setName(ConstantesPrueba.COMBO_OP);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rGrupoOperaciones = new javax.swing.ButtonGroup();
        tabbedPanel = new javax.swing.JTabbedPane();
        tbBotones = new javax.swing.JPanel();
        bSuma = new javax.swing.JButton();
        bResta = new javax.swing.JButton();
        bMultiplica = new javax.swing.JButton();
        bDivide = new javax.swing.JButton();
        Text1 = new javax.swing.JLabel();
        lResultB = new javax.swing.JLabel();
        top1b = new javax.swing.JTextField();
        top2b = new javax.swing.JTextField();
        tbRadio = new javax.swing.JPanel();
        top1r = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        lResultR = new javax.swing.JLabel();
        top2r = new javax.swing.JTextField();
        rSumar = new javax.swing.JRadioButton();
        rRestar = new javax.swing.JRadioButton();
        rMultiplicar = new javax.swing.JRadioButton();
        rDividir = new javax.swing.JRadioButton();
        cDecimales = new javax.swing.JCheckBox();
        bEqualR = new javax.swing.JButton();
        tbCombo = new javax.swing.JPanel();
        top1c = new javax.swing.JTextField();
        lResultC = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        top2c = new javax.swing.JTextField();
        cOperaciones = new javax.swing.JComboBox();
        bEqualC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bSuma.setText("+");
        bSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSumaActionPerformed(evt);
            }
        });

        bResta.setText("-");
        bResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRestaActionPerformed(evt);
            }
        });

        bMultiplica.setText("X");
        bMultiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMultiplicaActionPerformed(evt);
            }
        });

        bDivide.setText("/");
        bDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDivideActionPerformed(evt);
            }
        });

        Text1.setText("RESULTADO");

        lResultB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        lResultB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        top1b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top1bFocusGained(evt);
            }
        });

        top2b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top2bFocusGained(evt);
            }
        });

        javax.swing.GroupLayout tbBotonesLayout = new javax.swing.GroupLayout(tbBotones);
        tbBotones.setLayout(tbBotonesLayout);
        tbBotonesLayout.setHorizontalGroup(
            tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbBotonesLayout.createSequentialGroup()
                .addGroup(tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbBotonesLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lResultB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text1)
                            .addGroup(tbBotonesLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bMultiplica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(tbBotonesLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(top1b, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(top2b, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        tbBotonesLayout.setVerticalGroup(
            tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSuma)
                    .addComponent(top1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(top2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bResta)
                .addGap(18, 18, 18)
                .addComponent(bMultiplica)
                .addGap(18, 18, 18)
                .addComponent(bDivide)
                .addGap(47, 47, 47)
                .addComponent(Text1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lResultB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Botones", tbBotones);

        top1r.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top1rFocusGained(evt);
            }
        });

        Text3.setText("RESULTADO");

        lResultR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        top2r.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top2rFocusGained(evt);
            }
        });

        rGrupoOperaciones.add(rSumar);
        rSumar.setSelected(true);
        rSumar.setText("Sumar");
        rSumar.setActionCommand("SUMA");

        rGrupoOperaciones.add(rRestar);
        rRestar.setText("Restar");
        rRestar.setActionCommand("RESTA");

        rGrupoOperaciones.add(rMultiplicar);
        rMultiplicar.setText("Multiplicar");
        rMultiplicar.setActionCommand("MULTIPLICA");

        rGrupoOperaciones.add(rDividir);
        rDividir.setText("Dividir");
        rDividir.setActionCommand("DIVIDE");

        cDecimales.setText("Decimales");

        bEqualR.setText("=");
        bEqualR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEqualRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbRadioLayout = new javax.swing.GroupLayout(tbRadio);
        tbRadio.setLayout(tbRadioLayout);
        tbRadioLayout.setHorizontalGroup(
            tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbRadioLayout.createSequentialGroup()
                .addGroup(tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbRadioLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lResultR, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text3)))
                    .addGroup(tbRadioLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(top1r, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rRestar)
                            .addComponent(rSumar)
                            .addComponent(rMultiplicar)
                            .addComponent(rDividir)
                            .addComponent(cDecimales)
                            .addComponent(bEqualR, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(top2r, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        tbRadioLayout.setVerticalGroup(
            tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(top1r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(top2r, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSumar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rRestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rMultiplicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rDividir)
                .addGap(18, 18, 18)
                .addComponent(cDecimales)
                .addGap(28, 28, 28)
                .addComponent(bEqualR)
                .addGap(11, 11, 11)
                .addComponent(Text3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lResultR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Radio", tbRadio);

        top1c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top1cFocusGained(evt);
            }
        });

        lResultC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        Text2.setText("RESULTADO");

        top2c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                top2cFocusGained(evt);
            }
        });

        cOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUMA", "RESTA", "MULTIPLICA", "DIVIDE" }));

        bEqualC.setText("=");
        bEqualC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEqualCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbComboLayout = new javax.swing.GroupLayout(tbCombo);
        tbCombo.setLayout(tbComboLayout);
        tbComboLayout.setHorizontalGroup(
            tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbComboLayout.createSequentialGroup()
                .addGroup(tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbComboLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lResultC, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text2)))
                    .addGroup(tbComboLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(top1c, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEqualC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cOperaciones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(top2c, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        tbComboLayout.setVerticalGroup(
            tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbComboLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(top1c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(top2c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bEqualC)
                .addGap(131, 131, 131)
                .addComponent(Text2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lResultC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Combo", tbCombo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // <editor-fold defaultstate="collapsed" desc="Acciones">    
    private void bSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSumaActionPerformed
        if (!error(top1b, top2b, false)) {
            lResultB.setText("" + (int) (op1 + op2));
        }
    }//GEN-LAST:event_bSumaActionPerformed

    private void top1bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top1bFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top1bFocusGained

    private void top2bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top2bFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top2bFocusGained

    private void top1rFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top1rFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top1rFocusGained

    private void top2rFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top2rFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top2rFocusGained

    private void top1cFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top1cFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top1cFocusGained

    private void top2cFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_top2cFocusGained
        resetTextFieldsParams((JTextField) evt.getSource());
    }//GEN-LAST:event_top2cFocusGained

    private void bRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRestaActionPerformed
        if (!error(top1b, top2b, false)) {
            lResultB.setText("" + (int) (op1 - op2));
        }
    }//GEN-LAST:event_bRestaActionPerformed

    private void bMultiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMultiplicaActionPerformed
        if (!error(top1b, top2b, false)) {
            lResultB.setText("" + (int) (op1 * op2));
        }
    }//GEN-LAST:event_bMultiplicaActionPerformed

    private void bDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDivideActionPerformed
        if (!error(top1b, top2b, false)) {
            lResultB.setText("" + (int) (op1 / op2));
        }
    }//GEN-LAST:event_bDivideActionPerformed

    private void bEqualRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqualRActionPerformed
        double result;
        if (!error(top1r, top2r, cDecimales.isSelected())) {
            result=hazOperacion(rGrupoOperaciones.getSelection().getActionCommand());
            lResultR.setText(cDecimales.isSelected() ? new DecimalFormat("0.#########").format(result) : ("" + (int)result));
        }
    }//GEN-LAST:event_bEqualRActionPerformed

    private void bEqualCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEqualCActionPerformed
        double result;
        if (!error(top1c, top2c, false)) {
            result=hazOperacion(cOperaciones.getSelectedItem().toString());
            lResultC.setText("" + (int)result);
        }
    }//GEN-LAST:event_bEqualCActionPerformed
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Metodos control">    
    private boolean error(JTextField campo1, JTextField campo2, boolean decimal) {
        StringBuffer mensaje = new StringBuffer();//Se ha introducido un valor no numérico o No ha introducido valor (campo vacío)
        boolean error = false;
        error = actionError(campo1, campo2, decimal, error, mensaje);
        if (error) {
            JOptionPane.showMessageDialog(this, mensaje.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return error;
    }

    private boolean actionError(JTextField campo1, JTextField campo2, boolean decimal, boolean error, StringBuffer mensaje) {
        //cogeValor recibe true si es op1, false si es op2
        try {
            cogeValor(true, campo1, decimal);//El true es para notificar la recogida del primer valor "op1" y false para "op2"
        } catch (Exception w) {
            campo1.setBackground(Color.red);//Cambia el color de fondo
            campo1.setForeground(Color.white);//Cambia el color del texto
            error = true;
            mensaje.append(campo1.getText().equalsIgnoreCase("") ? "No ha introducido valor en la celda de la izquierda." : "Se ha introducido un valor no numérico o numérico en formato incorrecto en la celda de la izquierda.");
        }
        try {
            cogeValor(false, campo2, decimal);
        } catch (Exception w) {
            campo2.setBackground(Color.red);//Cambia el color de fondo
            campo2.setForeground(Color.white);//Cambia el color del texto
            error = true;
            mensaje.append(campo2.getText().equalsIgnoreCase("") ? (mensaje.length() == 0 ? "" : "\n") + "No ha introducido valor en la celda de la derecha." : (mensaje.length() == 0 ? "" : "\n") + "Se ha introducido un valor no numérico o numérico en formato incorrecto en la celda de la derecha.");
        }
        if (!error && !decimal) {
            op1 = Math.floor(op1);
            op2 = Math.floor(op2);
        }
        return error;
    }

    private void cogeValor(boolean op, JTextField campo, boolean decimal) throws Exception {
        if (decimal) {
            if (op) {
                op1 = Double.parseDouble(campo.getText());
            } else {
                op2 = Double.parseDouble(campo.getText());
            }
        } else {
            if (op) {
                op1 = Integer.parseInt(campo.getText());
            } else {
                op2 = Integer.parseInt(campo.getText());
            }
        }
    }

    public void resetTextFieldsParams(JTextField s) {
        s.setBackground(Color.white);
        s.setForeground(Color.black);
    }

    public double hazOperacion(String cadena) {
        double result=0;
        switch (Operacion.valueOf(cadena)) {
            case SUMA:
                result = op1 + op2;
                break;
            case RESTA:
                result = op1 - op2;
                break;
            case MULTIPLICA:
                result = op1 * op2;
                break;
            case DIVIDE:
                result = op1 / op2;
                break;
        }
        return result;
    }
    //</editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JButton bDivide;
    private javax.swing.JButton bEqualC;
    private javax.swing.JButton bEqualR;
    private javax.swing.JButton bMultiplica;
    private javax.swing.JButton bResta;
    private javax.swing.JButton bSuma;
    private javax.swing.JCheckBox cDecimales;
    private javax.swing.JComboBox cOperaciones;
    private javax.swing.JLabel lResultB;
    private javax.swing.JLabel lResultC;
    private javax.swing.JLabel lResultR;
    private javax.swing.JRadioButton rDividir;
    private javax.swing.ButtonGroup rGrupoOperaciones;
    private javax.swing.JRadioButton rMultiplicar;
    private javax.swing.JRadioButton rRestar;
    private javax.swing.JRadioButton rSumar;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JPanel tbBotones;
    private javax.swing.JPanel tbCombo;
    private javax.swing.JPanel tbRadio;
    private javax.swing.JTextField top1b;
    private javax.swing.JTextField top1c;
    private javax.swing.JTextField top1r;
    private javax.swing.JTextField top2b;
    private javax.swing.JTextField top2c;
    private javax.swing.JTextField top2r;
    // End of variables declaration//GEN-END:variables
}
