/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.reloj;

import static constantes.Constantes.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author dam2
 */
public class Reloj extends javax.swing.JFrame {

   private Timer t;
   private int hora;
   private int min;
   private int sec;
   private int mil;
   private int numeroVueltas;
    
    /**
     * Creates new form Reloj
     */
    public Reloj() {
        initComponents();
        setInitialValues();
        ponNombresVariables();
        t=new Timer(100,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                pintarCrono();
                mil++;
                if(mil>=10){
                    mil=0;
                    sec++;
                    if(sec>=60){
                        sec=0;
                        min++;
                        if(min>=60){
                            min=0;
                            hora++;
                        }
                    }
                }
            }
        });
        //t.setInitialDelay(0);
    }
    
    public void ponNombresVariables(){
        jHora.setName(HOUR);
        jMilliseconds.setName(MILLISECONDS);
        jMinuto.setName(MINUTES);
        jSegundo.setName(SECONDS);
        start.setName(START);
        pause.setName(PAUSE);
        reset.setName(RESET);
        lap.setName(LAP);
        jLabelVuelta1Timer.setName(VUELTA1);
        jLabelVuelta2Timer.setName(VUELTA2);
        jLabelVuelta3Timer.setName(VUELTA3);
    }
    
    public void pintarCrono(){
        jHora.setText(String.format("%02d",hora));
        jMinuto.setText(String.format("%02d",min));
        jSegundo.setText(String.format("%02d",sec));
        jMilliseconds.setText(Integer.toString(mil));
    }
    
    public void setInitialValues(){
        hora=0;
        min=0;
        sec=0;
        mil=0;
        numeroVueltas=0;
        jLabelVuelta1Timer.setText("Vuelta 1");
        jLabelVuelta2Timer.setText("Vuelta 2");
        jLabelVuelta3Timer.setText("Vuelta 3");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        lap = new javax.swing.JButton();
        jHora = new javax.swing.JLabel();
        jLabelDospuntos1 = new javax.swing.JLabel();
        jMinuto = new javax.swing.JLabel();
        jLabelDospuntos2 = new javax.swing.JLabel();
        jSegundo = new javax.swing.JLabel();
        jLabelPuntoMillesima = new javax.swing.JLabel();
        jMilliseconds = new javax.swing.JLabel();
        jLabelVuelta1 = new javax.swing.JLabel();
        jLabellVuelta2 = new javax.swing.JLabel();
        jLabelVuelta3 = new javax.swing.JLabel();
        jLabelVuelta1Timer = new javax.swing.JLabel();
        jLabelVuelta2Timer = new javax.swing.JLabel();
        jLabelVuelta3Timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        pause.setText("Pause");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        lap.setText("Lap");
        lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapActionPerformed(evt);
            }
        });

        jHora.setText("00");

        jLabelDospuntos1.setText(":");

        jMinuto.setText("00");

        jLabelDospuntos2.setText(":");

        jSegundo.setText("00");

        jLabelPuntoMillesima.setText(".");

        jMilliseconds.setText("0");

        jLabelVuelta1.setText("1:");

        jLabellVuelta2.setText("2:");

        jLabelVuelta3.setText("3:");

        jLabelVuelta1Timer.setText("Vuelta 1");

        jLabelVuelta2Timer.setText("Vuelta 2");

        jLabelVuelta3Timer.setText("Vuelta 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(start)
                        .addGap(53, 53, 53)
                        .addComponent(pause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(reset)
                        .addGap(42, 42, 42)
                        .addComponent(lap))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVuelta3)
                                    .addComponent(jLabellVuelta2)
                                    .addComponent(jLabelVuelta1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelVuelta1Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVuelta2Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVuelta3Timer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDospuntos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMinuto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDospuntos2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSegundo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelPuntoMillesima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMilliseconds)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHora)
                    .addComponent(jLabelDospuntos1)
                    .addComponent(jMinuto)
                    .addComponent(jLabelDospuntos2)
                    .addComponent(jSegundo)
                    .addComponent(jLabelPuntoMillesima)
                    .addComponent(jMilliseconds))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVuelta1)
                    .addComponent(jLabelVuelta1Timer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabellVuelta2)
                    .addComponent(jLabelVuelta2Timer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVuelta3)
                    .addComponent(jLabelVuelta3Timer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(pause)
                    .addComponent(reset)
                    .addComponent(lap))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        t.start();
    }//GEN-LAST:event_startActionPerformed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        t.stop();
    }//GEN-LAST:event_pauseActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        t.stop();
        setInitialValues();
        lap.setEnabled(true);
        pintarCrono();
    }//GEN-LAST:event_resetActionPerformed

    private void lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapActionPerformed
        int millisec=mil;
        int seconds=sec;
        int minutes=min;
        int hour=hora;
        switch(numeroVueltas){
            case 0:
                jLabelVuelta1Timer.setText(String.format("%02d:%02d:%02d.%01d", hour,minutes,seconds,millisec));
                break;
            case 1:
                jLabelVuelta2Timer.setText(String.format("%02d:%02d:%02d.%01d", hour,minutes,seconds,millisec));
                break;
            case 2:
                jLabelVuelta3Timer.setText(String.format("%02d:%02d:%02d.%01d", hour,minutes,seconds,millisec));
                lap.setEnabled(false);
                break;
        }
        numeroVueltas++;
    }//GEN-LAST:event_lapActionPerformed

    public int getMilliseconds(){
        return mil;
    }
    
    public int getSeconds(){
        return sec;
    }
    
    public int getMinutes(){
        return min;
    }
    
    public int getHours(){
        return hora;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reloj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reloj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jHora;
    private javax.swing.JLabel jLabelDospuntos1;
    private javax.swing.JLabel jLabelDospuntos2;
    private javax.swing.JLabel jLabelPuntoMillesima;
    private javax.swing.JLabel jLabelVuelta1;
    private javax.swing.JLabel jLabelVuelta1Timer;
    private javax.swing.JLabel jLabelVuelta2Timer;
    private javax.swing.JLabel jLabelVuelta3;
    private javax.swing.JLabel jLabelVuelta3Timer;
    private javax.swing.JLabel jLabellVuelta2;
    private javax.swing.JLabel jMilliseconds;
    private javax.swing.JLabel jMinuto;
    private javax.swing.JLabel jSegundo;
    private javax.swing.JButton lap;
    private javax.swing.JButton pause;
    private javax.swing.JButton reset;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
