/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import modelo.Imagen;
import control.ControlImagen;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import static constantes.Constantes.*;

/**
 *
 * @author Victor
 */
public class Vista extends javax.swing.JFrame {

    private ControlImagen controlImagen;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        controlImagen = new ControlImagen();
        configurar();
        ponerNombres();
        crearFicheros();
    }

    public void configurar() {
        jLabelIzquierdo2.setText("");
        jLabelIzquierdo1.setText("");
        jLabelCentral.setText("");
        jLabelDerecha1.setText("");
        jLabelDerecha2.setText("");
        panelImagenMostrar.setAlignmentX(Component.CENTER_ALIGNMENT);
        panelImagenMostrar.setAlignmentY(Component.CENTER_ALIGNMENT);
    }

    public void ponerNombres() {
        jLabelIzquierdo2.setName(LABEL_EXT_IZQUIERDA);
        jLabelIzquierdo1.setName(LABEL_IZQUIERDA);
        jLabelCentral.setName(LABEL_CENTRO);
        jLabelDerecha1.setName(LABEL_DERECHA);
        jLabelDerecha2.setName(LABEL_EXT_DERECHA);
        botonIzqCarrousel.setName(BOTON_IZQDA);
        botonDerCarrousel.setName(BOTON_DER);
        jFileChooser.setName(FILECHOOSER);
        jMenuArchivo.setName(MENU_ARCHIVO);
        jMenuItemAgregar.setName(MENU_AGREGAR);
        jMenuItemQuitar.setName(MENU_QUITAR);
        jMenuItemGuarda.setName(MENU_GUARDAR);
        jMenuItemCarga.setName(MENU_CARGAR);
        jMenu1.setName(MENU_IMAGEN);
        optionNormal.setName(MENU_NORMAL);
        optionBlurred.setName(MENU_BORROSO);
        optionWhiteBlack.setName(MENU_BLANCO_Y_NEGRO);
        jMenu3.setName(MENU_PINTAR_LINEA);
        opcionPintarLineaAI.setName(MENU_PINTAR_LINEA_DESDE_ARRIBA_IZQUIERDA);
        opcionPintarLineaAD.setName(MENU_PINTAR_LINEA_DESDE_ARRIBA_DERECHA);
        opcionPintarLineaC.setName(MENU_PINTAR_LINEA_CRUZ);
        jPopupMenu1.setName(PMENU);
        optionNormal1.setName(PMENU_NORMAL);
        optionBlurred1.setName(PMENU_BORROSO);
        optionWhiteBlack1.setName(PMENU_BLANCO_Y_NEGRO);
        jMenu4.setName(PMENU_PINTAR_LINEA);
        opcionPintarLineaAI1.setName(PMENU_PINTAR_LINEA_DESDE_ARRIBA_IZQUIERDA);
        opcionPintarLineaAD1.setName(PMENU_PINTAR_LINEA_DESDE_ARRIBA_DERECHA);
        opcionPintarLineaC1.setName(PMENU_PINTAR_LINEA_CRUZ);
        panelImagenMostrar.setName(PANEL_MOSTRAR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        opcionesImagen = new javax.swing.ButtonGroup();
        opcionesImagen1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        optionNormal1 = new javax.swing.JRadioButtonMenuItem();
        optionBlurred1 = new javax.swing.JRadioButtonMenuItem();
        optionWhiteBlack1 = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        opcionPintarLineaAI1 = new javax.swing.JMenuItem();
        opcionPintarLineaAD1 = new javax.swing.JMenuItem();
        opcionPintarLineaC1 = new javax.swing.JMenuItem();
        panelImagenMostrar = new view.PanelImagen();
        carrouselPanel = new javax.swing.JPanel();
        botonIzqCarrousel = new javax.swing.JButton();
        jLabelIzquierdo2 = new javax.swing.JLabel();
        jLabelIzquierdo1 = new javax.swing.JLabel();
        jLabelCentral = new javax.swing.JLabel();
        jLabelDerecha1 = new javax.swing.JLabel();
        jLabelDerecha2 = new javax.swing.JLabel();
        botonDerCarrousel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemQuitar = new javax.swing.JMenuItem();
        jMenuItemGuarda = new javax.swing.JMenuItem();
        jMenuItemCarga = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        optionNormal = new javax.swing.JRadioButtonMenuItem();
        optionBlurred = new javax.swing.JRadioButtonMenuItem();
        optionWhiteBlack = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        opcionPintarLineaAI = new javax.swing.JMenuItem();
        opcionPintarLineaAD = new javax.swing.JMenuItem();
        opcionPintarLineaC = new javax.swing.JMenuItem();

        jFileChooser.setName("FileChooser"); // NOI18N

        opcionesImagen1.add(optionNormal1);
        optionNormal1.setSelected(true);
        optionNormal1.setText("Normal");
        optionNormal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionNormal1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(optionNormal1);

        opcionesImagen1.add(optionBlurred1);
        optionBlurred1.setText("Borroso");
        optionBlurred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBlurred1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(optionBlurred1);

        opcionesImagen1.add(optionWhiteBlack1);
        optionWhiteBlack1.setText("Blanco y Negro");
        optionWhiteBlack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionWhiteBlack1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(optionWhiteBlack1);
        jPopupMenu1.add(jSeparator2);

        jMenu4.setText("Pintar Lineas");

        opcionPintarLineaAI1.setText("Desde arriba e Izquierda");
        opcionPintarLineaAI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaAI1ActionPerformed(evt);
            }
        });
        jMenu4.add(opcionPintarLineaAI1);

        opcionPintarLineaAD1.setText("Desde arriba y derecha");
        opcionPintarLineaAD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaAD1ActionPerformed(evt);
            }
        });
        jMenu4.add(opcionPintarLineaAD1);

        opcionPintarLineaC1.setText("En cruz");
        opcionPintarLineaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaC1ActionPerformed(evt);
            }
        });
        jMenu4.add(opcionPintarLineaC1);

        jPopupMenu1.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelImagenMostrar.setComponentPopupMenu(jPopupMenu1);
        panelImagenMostrar.setName("PanelMuestra"); // NOI18N
        panelImagenMostrar.setPreferredSize(new java.awt.Dimension(680, 680));

        javax.swing.GroupLayout panelImagenMostrarLayout = new javax.swing.GroupLayout(panelImagenMostrar);
        panelImagenMostrar.setLayout(panelImagenMostrarLayout);
        panelImagenMostrarLayout.setHorizontalGroup(
            panelImagenMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        panelImagenMostrarLayout.setVerticalGroup(
            panelImagenMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        getContentPane().add(panelImagenMostrar);

        carrouselPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 20));

        botonIzqCarrousel.setText("Retrocede");
        botonIzqCarrousel.setName("BotonIzq"); // NOI18N
        botonIzqCarrousel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzqCarrouselActionPerformed(evt);
            }
        });
        carrouselPanel.add(botonIzqCarrousel);

        jLabelIzquierdo2.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabelIzquierdo2.setPreferredSize(new java.awt.Dimension(80, 80));
        carrouselPanel.add(jLabelIzquierdo2);

        jLabelIzquierdo1.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabelIzquierdo1.setPreferredSize(new java.awt.Dimension(80, 80));
        carrouselPanel.add(jLabelIzquierdo1);

        jLabelCentral.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabelCentral.setName("LabelCentral"); // NOI18N
        jLabelCentral.setPreferredSize(new java.awt.Dimension(80, 80));
        carrouselPanel.add(jLabelCentral);

        jLabelDerecha1.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabelDerecha1.setPreferredSize(new java.awt.Dimension(80, 80));
        carrouselPanel.add(jLabelDerecha1);

        jLabelDerecha2.setMaximumSize(new java.awt.Dimension(80, 80));
        jLabelDerecha2.setPreferredSize(new java.awt.Dimension(80, 80));
        carrouselPanel.add(jLabelDerecha2);

        botonDerCarrousel.setText("Avanza");
        botonDerCarrousel.setName("BotonDer"); // NOI18N
        botonDerCarrousel.setPreferredSize(new java.awt.Dimension(84, 25));
        botonDerCarrousel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerCarrouselActionPerformed(evt);
            }
        });
        carrouselPanel.add(botonDerCarrousel);

        getContentPane().add(carrouselPanel);

        jMenuArchivo.setText("Archivo");
        jMenuArchivo.setName(""); // NOI18N

        jMenuItemAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-agregar-rec.jpg"))); // NOI18N
        jMenuItemAgregar.setText("Agregar");
        jMenuItemAgregar.setName(""); // NOI18N
        jMenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAgregar);

        jMenuItemQuitar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-remove-rec.jpg"))); // NOI18N
        jMenuItemQuitar.setText("Quitar");
        jMenuItemQuitar.setName(""); // NOI18N
        jMenuItemQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemQuitarActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemQuitar);

        jMenuItemGuarda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGuarda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-disquette-rec.jpg"))); // NOI18N
        jMenuItemGuarda.setText("Guarda");
        jMenuItemGuarda.setName("Guarda"); // NOI18N
        jMenuItemGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuardaActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemGuarda);

        jMenuItemCarga.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-carpeta-rec.jpg"))); // NOI18N
        jMenuItemCarga.setText("Carga");
        jMenuItemCarga.setName("Carga"); // NOI18N
        jMenuItemCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargaActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemCarga);

        jMenuBar1.add(jMenuArchivo);

        jMenu1.setText("Imágenes");
        jMenu1.setName("Imagenes"); // NOI18N

        opcionesImagen.add(optionNormal);
        optionNormal.setText("Normal");
        optionNormal.setName("Normal"); // NOI18N
        optionNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionNormalActionPerformed(evt);
            }
        });
        jMenu1.add(optionNormal);

        opcionesImagen.add(optionBlurred);
        optionBlurred.setText("Borroso");
        optionBlurred.setName("Borroso"); // NOI18N
        optionBlurred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionBlurredActionPerformed(evt);
            }
        });
        jMenu1.add(optionBlurred);

        opcionesImagen.add(optionWhiteBlack);
        optionWhiteBlack.setText("Blanco y Negro");
        optionWhiteBlack.setName("BlancoNegro"); // NOI18N
        optionWhiteBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionWhiteBlackActionPerformed(evt);
            }
        });
        jMenu1.add(optionWhiteBlack);
        jMenu1.add(jSeparator1);

        jMenu3.setText("Pintar Lineas");
        jMenu3.setName("Pintar"); // NOI18N

        opcionPintarLineaAI.setText("Desde arriba e Izquierda");
        opcionPintarLineaAI.setName("LineaAI"); // NOI18N
        opcionPintarLineaAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaAIActionPerformed(evt);
            }
        });
        jMenu3.add(opcionPintarLineaAI);

        opcionPintarLineaAD.setText("Desde arriba y derecha");
        opcionPintarLineaAD.setName("LineaAD"); // NOI18N
        opcionPintarLineaAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaADActionPerformed(evt);
            }
        });
        jMenu3.add(opcionPintarLineaAD);

        opcionPintarLineaC.setText("En cruz");
        opcionPintarLineaC.setName("LineaC"); // NOI18N
        opcionPintarLineaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionPintarLineaCActionPerformed(evt);
            }
        });
        jMenu3.add(opcionPintarLineaC);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarActionPerformed
        jFileChooser.setApproveButtonText("Abrir");
        jFileChooser.setDialogTitle("Abrir");
        jFileChooser.setMultiSelectionEnabled(true);
        int valor = jFileChooser.showOpenDialog(this);
        if (valor == 0) {
            File paths[] = jFileChooser.getSelectedFiles();
            for (File path : paths) {
                controlImagen.agregarImagen(new Imagen(path.getPath()));
            }
            if (controlImagen.getTamanoCarrousel() != 0) {
                pintarCarrousel(controlImagen.muestraCarrousel());
            } else {
                pintarCarrouselVacio();
            }
        }
        jFileChooser.setMultiSelectionEnabled(false);
    }//GEN-LAST:event_jMenuItemAgregarActionPerformed

    private void botonIzqCarrouselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzqCarrouselActionPerformed
        controlImagen.retrocederPosicion();
        if (controlImagen.getTamanoCarrousel() != 0) {
            pintarCarrousel(controlImagen.muestraCarrousel());
        } else {
            pintarCarrouselVacio();
        }
    }//GEN-LAST:event_botonIzqCarrouselActionPerformed

    private void botonDerCarrouselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerCarrouselActionPerformed
        controlImagen.avanzarPosicion();
        if (controlImagen.getTamanoCarrousel() != 0) {
            pintarCarrousel(controlImagen.muestraCarrousel());
        } else {
            pintarCarrouselVacio();
        }
    }//GEN-LAST:event_botonDerCarrouselActionPerformed

    private void jMenuItemGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardaActionPerformed
        jFileChooser.setApproveButtonText("Guardar");
        jFileChooser.setDialogTitle("Guardar");
        int valor = jFileChooser.showOpenDialog(this);
        if (valor == 0) {
            String path = jFileChooser.getSelectedFile().getPath();
            controlImagen.guardarCarrousel(path.endsWith(".json") ? path : path + ".json");
            jFileChooser.setSelectedFile(null);
        }
    }//GEN-LAST:event_jMenuItemGuardaActionPerformed

    private void jMenuItemCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargaActionPerformed
        jFileChooser.setApproveButtonText("Cargar");
        jFileChooser.setDialogTitle("Cargar");
        int valor = jFileChooser.showOpenDialog(this);
        if (valor == 0) {
            controlImagen.cargarCarrousel(jFileChooser.getSelectedFile().getPath());
        }
        if (controlImagen.getTamanoCarrousel() != 0) {
            pintarCarrousel(controlImagen.muestraCarrousel());
        } else {
            pintarCarrouselVacio();
        }
    }//GEN-LAST:event_jMenuItemCargaActionPerformed

    private void jMenuItemQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemQuitarActionPerformed
        controlImagen.quitarImagen();
        if (controlImagen.getTamanoCarrousel() != 0) {
            pintarCarrousel(controlImagen.muestraCarrousel());
        } else {
            pintarCarrouselVacio();
        }
    }//GEN-LAST:event_jMenuItemQuitarActionPerformed

    private void optionNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionNormalActionPerformed
        setNormal();
    }//GEN-LAST:event_optionNormalActionPerformed

    private void optionBlurredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBlurredActionPerformed
        setBlurred();
    }//GEN-LAST:event_optionBlurredActionPerformed

    private void optionWhiteBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionWhiteBlackActionPerformed
        setWB();
    }//GEN-LAST:event_optionWhiteBlackActionPerformed

    private void opcionPintarLineaAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaAIActionPerformed
        pintarAI();
    }//GEN-LAST:event_opcionPintarLineaAIActionPerformed

    private void opcionPintarLineaADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaADActionPerformed
        pintarAD();
    }//GEN-LAST:event_opcionPintarLineaADActionPerformed

    private void opcionPintarLineaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaCActionPerformed
        pintarC();
    }//GEN-LAST:event_opcionPintarLineaCActionPerformed

    private void optionNormal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionNormal1ActionPerformed
        setNormal();
    }//GEN-LAST:event_optionNormal1ActionPerformed

    private void optionBlurred1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionBlurred1ActionPerformed
        setBlurred();
    }//GEN-LAST:event_optionBlurred1ActionPerformed

    private void optionWhiteBlack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionWhiteBlack1ActionPerformed
        setWB();
    }//GEN-LAST:event_optionWhiteBlack1ActionPerformed

    private void opcionPintarLineaAI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaAI1ActionPerformed
        pintarAI();
    }//GEN-LAST:event_opcionPintarLineaAI1ActionPerformed

    private void opcionPintarLineaAD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaAD1ActionPerformed
        pintarAD();
    }//GEN-LAST:event_opcionPintarLineaAD1ActionPerformed

    private void opcionPintarLineaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionPintarLineaC1ActionPerformed
        pintarC();
    }//GEN-LAST:event_opcionPintarLineaC1ActionPerformed

    private void crearFicheros() {
        File fich = new File(".\\imagenes\\Grandes\\Normal");
        if (!fich.exists()) {
            fich.mkdirs();
        }
        fich = new File(".\\imagenes\\Grandes\\Blur");
        if (!fich.exists()) {
            fich.mkdirs();
        }
        fich = new File(".\\imagenes\\Grandes\\BlackAndWhite");
        if (!fich.exists()) {
            fich.mkdirs();
        }
        fich = new File(".\\imagenes\\Iconos\\Normal");
        if (!fich.exists()) {
            fich.mkdirs();
        }
        fich = new File(".\\imagenes\\Iconos\\Blur");
        if (!fich.exists()) {
            fich.mkdirs();
        }
        fich = new File(".\\imagenes\\Iconos\\BlackAndWhite");
        if (!fich.exists()) {
            fich.mkdirs();
        }
    }

    private void pintarCarrousel(ArrayList<Imagen> muestra) {
        switch (controlImagen.getImagenActual().getEstado()) {
            case PINTA_NORMAL:
                optionNormal.setSelected(true);
                optionNormal1.setSelected(true);
                break;
            case PINTA_BLUR:
                optionBlurred.setSelected(true);
                optionBlurred1.setSelected(true);
                break;
            case PINTA_BLACK_AND_WHITE:
                optionWhiteBlack.setSelected(true);
                optionWhiteBlack1.setSelected(true);
                break;
        }
        javax.swing.JLabel[] labels = {jLabelCentral, jLabelDerecha1, jLabelIzquierdo1, jLabelDerecha2, jLabelIzquierdo2};
        for (int i = 0; i < muestra.size(); i++) {
            labels[i].setIcon(controlImagen.getImagenDimensionada(muestra.get(i).getRutaImagenIcono()));
        }
        panelImagenMostrar.setImagen(controlImagen.getImagenDimensionadaPrincipal(muestra.get(0).getRutaImagenPrincipal()));
    }

    private void pintarCarrouselVacio() {
        javax.swing.JLabel[] labels = {jLabelCentral, jLabelDerecha1, jLabelIzquierdo1, jLabelDerecha2, jLabelIzquierdo2};
        Imagen im = new Imagen("src\\main\\resources\\imagenes\\imagenNoDisponible.png");
        for (int i = 0; i < 5; i++) {
            labels[i].setIcon(controlImagen.getImagenDimensionada(im.getRutaImagenIcono()));
        }
        panelImagenMostrar.setImagen(controlImagen.getImagenDimensionadaPrincipal(im.getRutaImagenPrincipal()));
    }

    public void setNormal() {
        controlImagen.getImagenActual().setEstado(PINTA_NORMAL);
        pintarCarrousel(controlImagen.muestraCarrousel());
    }

    public void setBlurred() {
        controlImagen.getImagenActual().setEstado(PINTA_BLUR);
        pintarCarrousel(controlImagen.muestraCarrousel());
    }

    public void setWB() {
        controlImagen.getImagenActual().setEstado(PINTA_BLACK_AND_WHITE);
        pintarCarrousel(controlImagen.muestraCarrousel());
    }

    public void pintarAI() {
        BufferedImage im = controlImagen.getImagenDimensionadaPrincipal(controlImagen.getImagenActual().getRutaImagenPrincipal());
        Graphics2D g = im.createGraphics();
        g.setColor(Color.red);
        g.drawLine(0, 0, im.getWidth(), im.getHeight());
        panelImagenMostrar.setImagen(im);
    }

    public void pintarAD() {
        BufferedImage im = controlImagen.getImagenDimensionadaPrincipal(controlImagen.getImagenActual().getRutaImagenPrincipal());
        Graphics2D g = im.createGraphics();
        g.setColor(Color.red);
        g.drawLine(im.getWidth(), 0, 0, im.getHeight());
        panelImagenMostrar.setImagen(im);
    }

    public void pintarC() {
        BufferedImage im = controlImagen.getImagenDimensionadaPrincipal(controlImagen.getImagenActual().getRutaImagenPrincipal());
        Graphics2D g = im.createGraphics();
        g.setColor(Color.red);
        g.drawLine(0, 0, im.getWidth(), im.getHeight());
        g.drawLine(im.getWidth(), 0, 0, im.getHeight());
        panelImagenMostrar.setImagen(im);
    }

    public ControlImagen getControlImagen() {
        return controlImagen;
    }

    public PanelImagen getPanelImagen() {
        return panelImagenMostrar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDerCarrousel;
    private javax.swing.JButton botonIzqCarrousel;
    private javax.swing.JPanel carrouselPanel;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabelCentral;
    private javax.swing.JLabel jLabelDerecha1;
    private javax.swing.JLabel jLabelDerecha2;
    private javax.swing.JLabel jLabelIzquierdo1;
    private javax.swing.JLabel jLabelIzquierdo2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemCarga;
    private javax.swing.JMenuItem jMenuItemGuarda;
    private javax.swing.JMenuItem jMenuItemQuitar;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem opcionPintarLineaAD;
    private javax.swing.JMenuItem opcionPintarLineaAD1;
    private javax.swing.JMenuItem opcionPintarLineaAI;
    private javax.swing.JMenuItem opcionPintarLineaAI1;
    private javax.swing.JMenuItem opcionPintarLineaC;
    private javax.swing.JMenuItem opcionPintarLineaC1;
    private javax.swing.ButtonGroup opcionesImagen;
    private javax.swing.ButtonGroup opcionesImagen1;
    private javax.swing.JRadioButtonMenuItem optionBlurred;
    private javax.swing.JRadioButtonMenuItem optionBlurred1;
    private javax.swing.JRadioButtonMenuItem optionNormal;
    private javax.swing.JRadioButtonMenuItem optionNormal1;
    private javax.swing.JRadioButtonMenuItem optionWhiteBlack;
    private javax.swing.JRadioButtonMenuItem optionWhiteBlack1;
    private view.PanelImagen panelImagenMostrar;
    // End of variables declaration//GEN-END:variables
}
