/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.trapograficovictormanueloviedo;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.Condition;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.UIDefaults;
import pañuelo.modelo.Arbitro;
import static pañuelo.modelo.Constantes.*;
import pañuelo.modelo.Niño;

/**
 *
 * @author dam2
 */
public class VistaPanuelo extends javax.swing.JFrame {
    private Timer t;
    private Map<String, JLabel> labelForNiño;
    private JLabel [] labelNiños;
    /**
     * Creates new form VistaPanuelo
     */
    public VistaPanuelo() {
        initComponents();
        jProgressBar2.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        UIDefaults defaults = new UIDefaults();
        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.blue));
        jProgressBar1.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        jProgressBar1.putClientProperty("Nimbus.Overrides", defaults);
        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.YELLOW));
        jProgressBar2.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        jProgressBar2.putClientProperty("Nimbus.Overrides", defaults);
        jProgressBar1.setMaximum(200);
        jProgressBar2.setMaximum(200);
        labelNiños=new JLabel[]{jLabel1E1,jLabel2E1,jLabel3E1,jLabel4E1,jLabel5E1,jLabel1E2,jLabel2E2,jLabel3E2,jLabel4E2,jLabel5E2};
        for(JLabel j:labelNiños){
            j.setOpaque(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel1E1 = new javax.swing.JLabel();
        jLabel2E1 = new javax.swing.JLabel();
        jLabel3E1 = new javax.swing.JLabel();
        jLabel4E1 = new javax.swing.JLabel();
        jLabel5E1 = new javax.swing.JLabel();
        jLabel1E2 = new javax.swing.JLabel();
        jLabel2E2 = new javax.swing.JLabel();
        jLabel3E2 = new javax.swing.JLabel();
        jLabel4E2 = new javax.swing.JLabel();
        jLabel5E2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelArbitroDice = new javax.swing.JLabel();
        jLabelNumeroArbitro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Equipo1");

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Equipo2");

        jLabel1E1.setText("n0");

        jLabel2E1.setText("n0");

        jLabel3E1.setText("n0");

        jLabel4E1.setText("n0");

        jLabel5E1.setText("n0");

        jLabel1E2.setText("n0");

        jLabel2E2.setText("n0");

        jLabel3E2.setText("n0");

        jLabel4E2.setText("n0");

        jLabel5E2.setText("n0");

        jLabel13.setText("Lado Equipo 1");

        jLabel14.setText("Lado Equipo2");

        jLabelArbitroDice.setText("Arbitro dice");

        jLabelNumeroArbitro.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1E1)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2E1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1E2)
                                .addGap(49, 49, 49)
                                .addComponent(jLabel2E2)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3E1)
                            .addComponent(jLabel3E2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4E2)
                            .addComponent(jLabel4E1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5E1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5E2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel14)))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(184, 184, 184)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelArbitroDice)
                        .addGap(73, 304, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelNumeroArbitro)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabelArbitroDice))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNumeroArbitro)
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel1E1)
                                    .addComponent(jLabel2E1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3E1)
                                        .addComponent(jLabel5E1))
                                    .addComponent(jLabel4E1))
                                .addGap(69, 69, 69)))
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(101, 101, 101)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1E2)
                        .addComponent(jLabel2E2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3E2)
                            .addComponent(jLabel5E2))
                        .addComponent(jLabel4E2)))
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setEnabled(false);
        for(int i=0;i<labelNiños.length;i++){
            labelNiños[i].setBackground(null);
        }
        Arbitro arbitro = new Arbitro();
        Niño n1 = new Niño("n1", arbitro);
        Niño n2 = new Niño("n2", arbitro);
        Niño n3 = new Niño("n3", arbitro);
        Niño n4 = new Niño("n4", arbitro);
        Niño n5 = new Niño("n5", arbitro);
        Niño n6 = new Niño("n6", arbitro);
        Niño n7 = new Niño("n7", arbitro);
        Niño n8 = new Niño("n8", arbitro);
        Niño n9 = new Niño("n9", arbitro);
        Niño n10 = new Niño("n10", arbitro);
        labelForNiño=new HashMap();
        try {
            TimeUnit.MILLISECONDS.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(VistaPanuelo.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<Niño>niños=arbitro.getNiños();
        int labelE1=0;
        int labelE2=5;
        for(int i=0;i<niños.size();i++){
            if(niños.get(i).getEquipo().equals(EQUIPO1)){
                labelForNiño.put(niños.get(i).getNombre(), labelNiños[labelE1]);
                labelNiños[labelE1].setText(niños.get(i).getNombre());
                labelE1++;
            }else{
                labelForNiño.put(niños.get(i).getNombre(), labelNiños[labelE2]);
                labelNiños[labelE2].setText(niños.get(i).getNombre());
                labelE2++;
            }
        }
        t=new Timer(100,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Niño[]corredores=arbitro.getCorredores();
                int corredor1=0;
                int corredor2=0;
                if(corredores[0]!=null&&corredores[1]!=null){
                    jLabelNumeroArbitro.setText(corredores[0].getNumeroPañuelo()+"");
                    labelForNiño.get(corredores[0].getNombre()).setBackground(Color.red);
                    labelForNiño.get(corredores[1].getNombre()).setBackground(Color.red);
                    corredor1=corredores[0].getMetrosRecorridos();
                    corredor2=corredores[1].getMetrosRecorridos();
                    boolean tieneTrapo1=corredores[0].isTienePañuelo();
                    boolean tieneTrapo2=corredores[1].isTienePañuelo();
                    boolean volver1=corredores[0].isVolver();
                    boolean volver2=corredores[1].isVolver();
                    corredor1=(corredor1>100&&corredor1<110)?100:(tieneTrapo2&&volver1)?(200-corredor1):corredor1;
                    corredor2=(corredor2>100&&corredor2<110)?100:(tieneTrapo1&&volver2)?(200-corredor2):corredor2;
                    if(corredores[0].getEquipo().equals(EQUIPO1)){
                        jProgressBar1.setValue(corredor1);
                        jProgressBar2.setValue(corredor2);
                    }else{
                        jProgressBar2.setValue(corredor1);
                        jProgressBar1.setValue(corredor2);
                    }
                    Niño[]ganadores=arbitro.getGanadores();
                    for(int i=0;i<ganadores.length;i++){
                        if(ganadores[i]!=null){
                            labelForNiño.get(ganadores[i].getNombre()).setBackground(Color.green);
                        }
                    }
                }else{
                    Niño[]ganadores=arbitro.getGanadores();
                    for(int i=0;i<ganadores.length;i++){
                        if(ganadores[i]!=null){
                            labelForNiño.get(ganadores[i].getNombre()).setBackground(Color.green);
                        }
                    }
                    jProgressBar2.setValue(0);
                    jProgressBar1.setValue(0);
                    if(arbitro.isTerminado()){
                        t.stop();
                        jButton1.setEnabled(true);
                    }
                }
                
            }
        });
        t.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPanuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPanuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPanuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPanuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPanuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel1E1;
    private javax.swing.JLabel jLabel1E2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2E1;
    private javax.swing.JLabel jLabel2E2;
    private javax.swing.JLabel jLabel3E1;
    private javax.swing.JLabel jLabel3E2;
    private javax.swing.JLabel jLabel4E1;
    private javax.swing.JLabel jLabel4E2;
    private javax.swing.JLabel jLabel5E1;
    private javax.swing.JLabel jLabel5E2;
    private javax.swing.JLabel jLabelArbitroDice;
    private javax.swing.JLabel jLabelNumeroArbitro;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    // End of variables declaration//GEN-END:variables
}
